spring:
  application:
    name: cloud-file-storage
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:cloud_file_storage}?currentSchema=auth
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false

minio:
  url: ${MINIO_HOST:http://localhost}:${MINIO_PORT_API:9000}
  access-key: ${MINIO_ROOT_USER:admin}
  secret-key: ${MINIO_ROOT_PASSWORD:password}
  bucket: ${MINIO_BUCKET_NAME:root}
