spring:
  application:
    name: cloud-file-storage
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:cloud_file_storage}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    properties.hibernate:
      show_sql: false
      format_sql: false
      hbm2ddl.auto: validate
    open-in-view: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}
      timeout: 5000
  session:
    timeout: 30m

server:
  tomcat:
    max-swallow-size: 11MB
    max-http-form-post-size: 101MB

logging:
  level:
    org.springframework: "WARN"
    org.hibernate: "WARN"
    com.craftelix: "INFO"

minio:
  url: http://${MINIO_HOST:localhost}:${MINIO_PORT_API:9000}
  access-key: ${MINIO_ROOT_USER:admin}
  secret-key: ${MINIO_ROOT_PASSWORD:password}
  bucket: ${MINIO_BUCKET_NAME:root}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
    prometheus:
      enabled: true

app:
  user:
    name: ${DEFAULT_ADMIN_NAME:admin}
    password: ${DEFAULT_ADMIN_PASSWORD:pass123}